apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  annotations:
    # see https://argo-cd.readthedocs.io/en/latest/operator-manual/high_availability/#manifest-paths-annotation
    # see https://github.com/argoproj/argo-cd/blob/2e6e6cfc1244ebcddeb2f0ff153dcfe55a3abe11/util/app/path/path.go#L144
    argocd.argoproj.io/manifest-generate-paths: /argo-apps.yaml;/apps;/apps/*;/apps/*/*
spec:
  project: default
  destination:
    name: in-cluster
    namespace: production
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    # TODO: uncomment after updating ArgoCD
    # retry:
    #   refresh: true
  source:
    path: apps
    repoURL: "https://github.com/buzz-labs/k8s.git"
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
