{{- if .Values.sealedSecrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec: 
  encryptedData:
{{- if .Values.extraEnvSecrets }}
{{ toYaml .Values.extraEnvSecrets | indent 4 }}
{{- end }}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "portal.fullname" . }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.extraEnvSecrets }}
{{ toYaml .Values.extraEnvSecrets | indent 2 }}
{{- end }}
{{- end -}}
